### PR TITLE
Make the mavfft_isb accessible to other programs

### PR DESCRIPTION
**Pull request by Gone4Dirt**
mavfft_isb is a pretty useful tool.  I like to use it as part of other tools.  I also wanted to integrate it into the MavExplorer partly to add the functionality of this tool into MavExplorer and to reduce duplication.  This PR will enable that.

Functionality should be unchanged so it can be used as it was for everyone that used it previously.

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]
@Gone4Dirt its impossible for me to review 😄 presumably you have tested this on some logfiles in which case I approve

It's unfortunate this will massively conflict with my FFT heatmap change, but I am not going to finish that anytime soon.

**Comment by Gone4Dirt** [comment]
Yeah, sorry the diff is horrendous.

Basically moved the function into a class.  Made all of the args variables withing that class then added a main == name check and moved the arg parser after that.

Tested all args and all are working as before.

**Comment by peterbarker** [comment]
> Yeah, sorry the diff is horrendous.

Hiding whitespace changes makes it much more palatable.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
