### PR TITLE
Travis CI: Add more flake8 tests

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by peterbarker** [comment]
A bit of work to do here yet.

Note we do intentionally pollute our namespace in some places so that evaluated expressions don't need to specify a namespace.  e.g. `graph sqrt(RANGEFINDER.time_us)`

**Comment by peterbarker** [comment]
I've rebased this on master, squashed it and removed the upgrade to Python 3.8

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by cclauss** [comment]
Why no Py38 on focal instead of xenial?  Py39 is final candidate 1 can be tested with "3.9-dev"

**Comment by peterbarker** [comment]
On Fri, 21 Aug 2020, Christian Clauss wrote:

> Why no Py38 on focal instead of xenial? Py39 is final candidate 1 can be tested with "3.9-dev"

I took on @khancyr's comment, and noted that moving Python forward wasn't 
related to the title of the PR....

It's also kind of important to ensure we don't inadvertently break old 
installations.  Perhaps for pymavlink we could afford to use a travis 
matrix?

**Pull request merged**
