### PR TITLE
Better ci

### PR DESCRIPTION
**Pull request by khancyr**
This add pre-commit as part of CI. 
this tool allow to set check easy and add them localy on git-hook for better coding and not wait CI to trigger failure.

The PR also add : 
pyproject.toml to have commom place for python checker/linter tools
.editorconfig: to try to have all ide configured the same 
add .idea on .gitignore for those that are using pyCharm or Clion
add .flake8 config file for local developpement
add shellcheck to CI : it will only fail if the shell script got fatal error.

Correct Line Ending mixing on files : we should have only LF
Correct permission on files
Remove python shebang on python library as they aren't executable

### CODE REVIEW

**Review by tridge — CHANGES_REQUESTED** [review]
needs to be info on this in the README.md, and add a run_code_checks.sh which runs the checks, and gives a sensible error message if a required tool isn't available

**Review by peterbarker — CHANGES_REQUESTED** [review]
There's a couple of these "APM"s

Sorry, didn't get far here.

**Comment by tridge** [comment]
lets do this on EU dev call

**Comment by peterbarker** [comment]
Looked briefly at this and it definitely needs a rebase.  Also tridge marked it but wasn't available.

**Pull request closed without merging**
