### PR TITLE
Add grams to SI_Units

### PR DESCRIPTION
**Pull request by hamishwillee**
Required for https://github.com/mavlink/mavlink/pull/1072

### CODE REVIEW

**Comment by hamishwillee** [comment]
@amilcarlucas Could you please push this in.

**Comment by hamishwillee** [comment]
> technically kg is the SI unit, right?

I *think* the "base" unit is the kg, and SI refer to gram and milligram as "derived units". Either way though, we have other "non SI" units in there where it is pragmatic to do so - as in this case.

**Comment by amilcarlucas** [comment]
done, thanks

**Comment by hamishwillee** [comment]
Thanks @amilcarlucas ! appreciate this.

**Pull request merged**
