### PR TITLE
Fixed bugs with Python 3.

### PR DESCRIPTION
**Pull request by JloveU**

### CODE REVIEW

**Comment by khancyr** [comment]
Hello,

Could you share the error you get with Python 3 ?

**Comment by JloveU** [comment]
In Python 3:

```
struct.error: argument for 's' must be a bytes object
```

**Comment by peterbarker** [comment]
@JloveU Could you provide instructions on how to reproduce the error, please?

**Comment by amilcarlucas** [comment]
Can you please rebase this

**Comment by pietrodn** [comment]
I ran the DroneKit SITL tests and [they are passing](https://github.com/ArduPilot/pymavlink/pull/141#issuecomment-431562224) with the latest pymavlink version. This PR may be unneeded.

**Pull request closed without merging**
