### PR TITLE
travis: Add trailing space test in flake8

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by peterbarker** [comment]
I'm in favour.

However, @tridge doesn't use `(add-hook 'python-mode-hook (lambda () (setq show-trailing-whitespace 1)))`, and his patches often include trailing whitespace.  That means he doesn't see it as a problem, and adding a regression test which fails his patches might not be the best thing for me to merge :-)

**Comment by cclauss** [comment]
After he submits three messages that fail the test, he will probably start to learn that trailing whitespace is no longer accepted ;-)

**Comment by patrickelectric** [comment]
Can you take a look on this PR to merge it @tridge ?

**Comment by patrickelectric** [comment]
is there something holding this PR ?
Can it be merged, please ?

**Pull request merged**
