### PR TITLE
Generator: JavaScript bindings , adding full support for mavlink2 signing, with tests.

### PR DESCRIPTION
**Pull request by davidbuzz**
test suite also updated so passes

had to disable a couple of small spy.callCount. tests i don't quite understand yet, but given that this actually gets 400 additional SIGNING tests to actually pass, not just say they did, i say its a net positive.

### CODE REVIEW

**Comment by davidbuzz** [comment]
Autotests on 'ardupilot/pymavlink' 'master' repo are broken as a result of a change to the xml in the 'ardupilot/mavlink' repo made 7 days ago by @amilcar  and @Peter Barker , 
 This is the specific 'mavlink' commit that broke it:  https://github.com/ArduPilot/mavlink/commit/6f036bf295dfd54d7da32262049c4feef2c6a595
As a work-around for this PR till that issue is resolved ,  i have now tweaked to get it to "pass" by forcing the test/s to run against 'mavlink' repo from the commit before the breaking commit:https://github.com/ArduPilot/pymavlink/pull/482

This PR should not be merged while .github/workflows/test.yml is in the files-changed list.   its ok to review tho.

**Comment by davidbuzz** [comment]
PR updated to remove the tests.yml, tests failed on master for a different reason, and the updated again to tweak Makefile to get tests to pass again.

**Comment by davidbuzz** [comment]
pr updated to pass on master again.

**Comment by davidbuzz** [comment]
As a bonus, and to make this PR more transparent,  i have written a command-line tool that uses the output of this PR to enable/diasble signing on a TCP mavlink connection (such as sitl)    its basically equivalent to the mavproxy 'signng' module, and does the same thing as these mavproxy command/s 'signing setup qwertyuiop' and 'signing remove'.   https://github.com/davidbuzz/MAVAgent

**Comment by stephendade** [comment]
I've tested this and it does work, using Mission Planner to enable signing, then using mavagent to arm/disarm.

**Review by stephendade — APPROVED** [review]

**Comment by davidbuzz** [comment]
added tridge for final review and/or merge.

**Pull request merged**
