### PR TITLE
Add optional units and bitmask fields to message definitions

### PR DESCRIPTION
**Pull request by amilcarlucas**
This will simplify machine parsing and presentation of data

### CODE REVIEW

**Comment by OXINARF** [comment]
This is a duplicate of #7

**Comment by OXINARF** [comment]
Actually this puts it on fields, instead of just command params. But I think it is just a small extension of #7 and should be discussed there.

**Comment by amilcarlucas** [comment]
No, this is not duplicate. This one is for all messages, not just for MAV_CMD. Please reopen.

**Comment by magicrub** [comment]
This is blocking https://github.com/mavlink/mavlink/pull/663

**Comment by OXINARF** [comment]
@amilcarlucas Like I said, this adds it to fields, #7 to command params. But the idea is the same and #7 has much more attributes. What would be the reason to keep two PRs open with the same idea?

**Comment by tridge** [comment]
i will look at merging the two PRs

**Comment by tridge** [comment]
merged, thanks!

**Pull request closed without merging**
