### PR TITLE
Travis CI: Upgrade Node.js and Python

### PR DESCRIPTION
**Pull request by cclauss**
@peterbarker
* https://nodejs.org/en/about/releases/
* https://www.python.org/download/pre-releases/

~Python 3.9 fc1 is failing because numpy is not installed.~

`bytes` is a Python built-in data types so let's use `bytes_array` as the variable name.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Can you squash some of the commits together?

**Comment by davidbuzz** [comment]
if this is squashed into a single commit I think its good to merge.

**Comment by peterbarker** [comment]
@cclauss needs a rebase.  Things must be moving fast if this was good to merge 4 hours ago :-)

@cclauss be aware we've most of our CI onto github actions.  Our Python tests probably stayed put.

**Comment by cclauss** [comment]
After this lands, I would be happy to rewrite as a GitHub Action if that would help.

Any plans to remove support for legacy Python?

**Comment by khancyr** [comment]
Nope, not for now. We still support python2 an ubuntu xenial that is python 3.5. so we cannot remove anything

**Comment by cclauss** [comment]
Legacy Python is Python 2.

**Comment by peterbarker** [comment]
On Sun, 1 Nov 2020, Christian Clauss wrote:

> After this lands, I would be happy to rewrite as a GitHub Action if that would help.
> 
> Any plans to remove support for legacy Python?

As in Python2 or anything pre 3.9?  :-)

We don't have plans to remove support for Python2.  We can't really, when 
you have Ubuntu LTS releases out there people are quite happily using - 
up-and-breaking their Python2 setups would be a bit unfriendly.

That being said - its going to be a glorious day when we can go through 
and nuke all of the Python2 compatability.  That day might come before all 
of the LTSs have expired....

**Comment by cclauss** [comment]
Can this please get a review?

**Comment by peterbarker** [comment]
Merged after some local testing and reports it fixes all sorts of things for MacOSX users.

Thanks @cclauss !

**Pull request merged**
