### PR TITLE
This adds a conditional that prevents unicode values from being added as float values.

### PR DESCRIPTION
**Pull request by QuPsi**
Continued work from

https://github.com/ArduPilot/pymavlink/pull/435

### CODE REVIEW

**Comment by peterbarker** [comment]
Can't tell you how much I love Python2 vs Python3 shenanigans.

From: https://github.com/ArduPilot/pymavlink/blob/master/DFReader.py#L238

```
        is_py2 = sys.version_info < (3,0)
```

```
            if is_py2:
                if isinstance(v,unicode): # NOQA
                    v = str(v)
            else:
                if isinstance(v,str):
```

**Comment by peterbarker** [comment]
Not sure what's up with that extra commit.  Seems out-of-place.

**Comment by QuPsi** [comment]
That was my mistake. I had committed an nonupdated version of the file and @mday299 was walking me through it. 

Great find on the python differences. That definitely seems to be the root of the issue!

**Comment by stephendade** [comment]
Yes, you'll need to remove that commit. Not sure how it got in there - possibly rebasing gone wrong.

**Comment by peterbarker** [comment]
@QuPsi are you still chasing this one?

**Comment by QuPsi** [comment]
Made an even simpler change.... just changed the values to 'str'.

I tried to implement your suggestion @peterbarker , however, simply having the work 'unicode' in the script upset versions >3.0.

The checks have passed and the script runs as intended on my side.

**Comment by peterbarker** [comment]
I can see code which is run later under this which is wondering if the type is `list`.  Since you've just forced it to string, that can never be the case now, so I don't think this change can be correct.

Note `DFReader.py` - which I know works under both Python2 and Python3 - uses `unicode` bare: https://github.com/ArduPilot/pymavlink/blob/master/DFReader.py#L239

**Comment by QuPsi** [comment]
@peterbarker Have a look at my latest commit when you can please. I think I got it now.

**Comment by peterbarker** [comment]
@QuPsi looks solid.

Has it been tested on both Py2 and Py3?

**Comment by peterbarker** [comment]
Please squash the commits down into a single commit.  Let me know if you'd like some direction on how to do that (or let me know and I'll do it before merging)

**Comment by QuPsi** [comment]
Ok, I think I got the commits squashed now and yes, tested in both py2 and py3!

**Comment by peterbarker** [comment]
I've touched up the commit message a bit and removed some introduced whitespace.  Will merge once CI is done.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by QuPsi** [comment]
Thank you so much! Learned a lot! I really appreciate the assistance!

**Comment by mday299** [comment]
Is this scheduled to be pulled upstream into mavlink and then into ardupilot soon?

**Comment by peterbarker** [comment]
@mday299 tridge was muttering about doing another pymavlink release recently, but there's no schedule as such.

**Pull request merged**
