### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by khancyr**
This is the github action for pymavlink.

Unfortunately, there is an error on the posix test as there are a lot of address-of-packed-member warning ...
I am not sure how to fix that

### CODE REVIEW

**Comment by peterbarker** [comment]
On Fri, 13 Nov 2020, Pierre Kancir wrote:

> Unfortunately, there is an error on the posix test as there is a lot of address-of-packed-member warning ...

Try rebasing?

**Comment by khancyr** [comment]
Oh... Damned this was merge when I was working on the PR. I will rebase and it should be fine !

**Comment by khancyr** [comment]
rebased

**Comment by davidbuzz** [comment]
lgtm

**Review by davidbuzz — APPROVED** [review]

**Comment by tridge** [comment]
we need to work out why it didn't run for this PR

**Pull request merged**
