### PR TITLE
update gps leap seconds to the correct value

### PR DESCRIPTION
**Pull request by davidbuzz**

### CODE REVIEW

**Comment by davidbuzz** [comment]
i'd like to also mention that there are a number of other, better implementation/s that could replace this one ( ie going from gps time to utc time and back again ), and i've run a number of these as tests in this gist....   https://gist.github.com/davidbuzz/df4113f22dd0df5f3787b644ed6c5db1

**Comment by davidbuzz** [comment]
good reference website: http://leapsecond.com/java/gpsclock.htm

**Comment by tridge** [comment]
a more future proof soln would be nice, but until then this is good, thanks!

**Comment by davidbuzz** [comment]
i'm just just leaving a note for future me, or anyone else that comes to this issue...  check the code in my mentioned gist for samples that could be massaged into something better if/when it's needed.

**Pull request merged**
