### PR TITLE
travis.yml: Test message generation for all languages

### PR DESCRIPTION
**Pull request by kartikmohta**
C++11 generation fails in Python 3, requires #84 to be merged.

Swift message generation fails due to `MAVLink.swift` not being installed.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
looks good to me. LGTM

**Comment by cclauss** [comment]
LGTM  This important change helps us find issues.

**Comment by peterbarker** [comment]
I like the idea.

However, it is currently causing travis to fall over - with a generation failure, oddly enough.

**Comment by kartikmohta** [comment]
@peterbarker I added the tests to travis.yml to catch these exact failures.

**Comment by cclauss** [comment]
@kartikmohta this is really great stuff!  I believe that Peter's question was: __How do we fix__
* https://travis-ci.org/ArduPilot/pymavlink/jobs/266406798#L1483
* https://travis-ci.org/ArduPilot/pymavlink/jobs/266406798#L1612
__so that we can check in the changes in this PR?__

**Comment by kartikmohta** [comment]
That should fix the Python 2 build, need #84 to fix Python 3 build.

**Comment by peterbarker** [comment]
On Wed, 6 Sep 2017, Kartik Mohta wrote:

> That should fix the Python 2 build, need #84 to fix Python 3 build.

I've pulled in #84, please rebase and squash as appropriate.

**Comment by kartikmohta** [comment]
Just curious, is there any action from my side pending for this to be merged?

**Comment by peterbarker** [comment]
Slightly changed a commit message and merged, thanks!

**Pull request closed without merging**
