### PR TITLE
Add a .pylintrc file

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by peterbarker** [comment]
How do the rules interact with the flake8 tests which we already do?

**Comment by amilcarlucas** [comment]
They do not, pylint is much more compreensive than flake8 and it runs a lot slower. This file is just to run pylint localy for now.
Once more of the code gets linted, we can automate this and activate fail on errors.

**Comment by amilcarlucas** [comment]
BTW better than flake8 is ruff

**Comment by tridge** [comment]
ruff sounds like better option, pylint is too slow

**Pull request closed without merging**
