### PR TITLE
mavlink_start_checksum() eliminate possibility of unaligned memory access

### PR DESCRIPTION
**Pull request by dagar**
@peterbarker here's another one. https://github.com/ArduPilot/pymavlink/pull/267

image

### CODE REVIEW

**Comment by peterbarker** [comment]
@dagar Have to check this one with tridge.  Looks logically correct, I'd just like to check for performance concerns.  Correctness can wait ;-)

**Comment by peterbarker** [comment]
Sorry, should provide an update here.

I asked tridge to look at this and he decided to check the root cause of the problem - packing these structures.  He was generally confident that with a little finessing we could stop packing these structures at all without impact, negating the need to create stack variables here.

**Comment by Brooce** [comment]
I just wanted to confirm that the bug exists (caused a HardFault handler ISR on my custom STM32 application) and the proposed solution solved it for Mavlink1 libraries.  For Mavlink2 however, the problem occurred in another place - in "mavlink_finalize_message_buffer" function. I have fixed it with analogous approach at the topmost level.

I'm not sure how to PR into a submodule and don't have the time to deal with it now, so here's just a quick little patch if anyone wants to make use of it:
[0001-Mavlink_helpers-Added-separate-variable-for-checksum.patch.txt](https://github.com/ArduPilot/pymavlink/files/2956520/0001-Mavlink_helpers-Added-separate-variable-for-checksum.patch.txt)

**Comment by dagar** [comment]
@Brooce that one should have been fixed in https://github.com/ArduPilot/pymavlink/pull/267.
I've rebased this PR on current master, could you try again?

**Comment by dagar** [comment]
> I asked tridge to look at this and he decided to check the root cause of the problem - packing these structures. He was generally confident that with a little finessing we could stop packing these structures at all without impact, negating the need to create stack variables here.

@peterbarker any update on this effort? Unless it's currently underway I would propose merging this in the meantime. The performance difference seemed to be negligible.

**Comment by tridge** [comment]
I do want to switch to unpacked structures in the future, but I agree with this as a quick fix. Merging

**Comment by dagar** [comment]
Thanks, I'll update https://github.com/mavlink/mavlink now.

**Comment by julianoes** [comment]
Related to #5.

**Pull request merged**
