### PR TITLE
Generator: Update Java MAVLink2 support

### PR DESCRIPTION
**Pull request by kellyschrock**
Get Java support for Mavlink2 working

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Can you please squash commits 3,4 and 5 into commit1 ?

**Comment by rrr6399** [comment]
FYI: Submitted this pull request to fix a bug I found and I merged in master as well to work with the current scripts:
https://github.com/kellyschrock/pymavlink/pull/1

**Comment by amilcarlucas** [comment]
@rrr6399 You are already the third person that works on this. It makes it obvious that people want this and that it is currently bitroting.

Can you do a clean PR with a bit of squashing?

**Comment by HefnySco** [comment]
This [git](https://github.com/HefnySco/Mavlink2_JAVA) contains working version of these classes. Although it is not auto generated but it works. I wish you find it useflu.

**Comment by rrr6399** [comment]
I'm looking into a couple of bugs:

1.) When using the MAVLink 2 library to send MAVLink1 messages, the message length is being set to the MAVLink 2 message size and CRC is added right after the MAVLink 1 payload with 0s being added after the CRC. I think the length should be set to the V1 message size. 
(See https://github.com/kellyschrock/pymavlink/blob/pr/127/generator/mavgen_java.py#L467)

2.) When setting isMavlink2=true in the message inherited from MAVLinkMessage, it doesn't get propagated to MAVLinkPacket when encoding the message.

**Comment by rrr6399** [comment]
Setting the payload length the current position of the ByteBuffer after writing the payload to the buffer worked:
src/com/MAVLink/MAVLinkPacket.java | 16 +++++++++-------
 1 file changed, 9 insertions(+), 7 deletions(-)

diff --git a/src/com/MAVLink/MAVLinkPacket.java b/src/com/MAVLink/MAVLinkPacket.java
index a6e140b..89ba295 100644
--- a/src/com/MAVLink/MAVLinkPacket.java
+++ b/src/com/MAVLink/MAVLinkPacket.java
@@ -169,6 +169,7 @@ public class MAVLinkPacket implements Serializable {
      * Update CRC for this packet.
      */
     public void generateCRC() {
+        final int payloadSize = payload.size();
         if(crc == null) {
             crc = new CRC();
         } else {
@@ -176,7 +177,7 @@ public class MAVLinkPacket implements Serializable {
         }
 
         if(isMavlink2) {
-            crc.update_checksum(len);
+            crc.update_checksum(payloadSize);
             crc.update_checksum(incompatFlags);
             crc.update_checksum(compatFlags);
             crc.update_checksum(seq);
@@ -186,7 +187,7 @@ public class MAVLinkPacket implements Serializable {
             crc.update_checksum(msgid >>> 8);
             crc.update_checksum(msgid >>> 16);
         } else {
-            crc.update_checksum(len);
+            crc.update_checksum(payloadSize);
             crc.update_checksum(seq);
             crc.update_checksum(sysid);
             crc.update_checksum(compid);
@@ -195,7 +196,6 @@ public class MAVLinkPacket implements Serializable {
 
         payload.resetIndex();
 
-        final int payloadSize = payload.size();
         for (int i = 0; i < payloadSize; i++) {
             crc.update_checksum(payload.getByte());
         }
@@ -221,20 +221,22 @@ public class MAVLinkPacket implements Serializable {
      */
     public byte[] encodePacket() {
         int bufLen;
+		int payloadSize = payload.size();
         if(isMavlink2) {
-            bufLen = MAVLINK2_HEADER_LEN + len + 2;
+            bufLen = MAVLINK2_HEADER_LEN + payloadSize + 2;
 
             //TODO: implement signature, maybe in encodeSignedPacket()
             //bufLen = MAVLINK2_HEADER_LEN + len + 2 + Signature.MAX_SIGNATURE_SIZE;
         } else {
-            bufLen = MAVLINK1_HEADER_LEN + len + 2;
+            bufLen = MAVLINK1_HEADER_LEN + payloadSize + 2;
         }
         byte[] buffer = new byte[bufLen];
+
         
         int i = 0;
         if(isMavlink2) {
             buffer[i++] = (byte) MAVLINK2_STX;
-            buffer[i++] = (byte) len;
+            buffer[i++] = (byte) payloadSize;
             buffer[i++] = (byte) incompatFlags;
             buffer[i++] = (byte) compatFlags;
             buffer[i++] = (byte) seq;
@@ -245,7 +247,7 @@ public class MAVLinkPacket implements Serializable {
             buffer[i++] = (byte) ((msgid >>> 16) & 0XFF);
         } else {
             buffer[i++] = (byte) MAVLINK1_STX;
-            buffer[i++] = (byte) len;
+            buffer[i++] = (byte) payloadSize;
             buffer[i++] = (byte) seq;
             buffer[i++] = (byte) sysid;
             buffer[i++] = (byte) compid;

**Comment by HefnySco** [comment]
> This [git](https://github.com/HefnySco/Mavlink2_JAVA) contains working version of these classes. Although it is not auto generated but it works. I wish you find it useful.

finally I have updated the generator in this [pull request](https://github.com/ArduPilot/pymavlink/pull/317).
I write this here because my updates is heavily dependent on this thread.

**Comment by magicrub** [comment]
closing this in favor of https://github.com/ArduPilot/pymavlink/pull/323

**Pull request closed without merging**
