### PR TITLE
Change mavutil.py license from GPLv3+ to LGPLv3+

### PR DESCRIPTION
**Pull request by amilcarlucas**
This allows this file to be used by dronekit-python, MavRos and other similar software.

I will contact the other commiters to this file per e-mail, but I would like to get the OK from the reviewers here first. The full list is bellow, it it be updated with the answers from the devs.
- [x]  1 Alex Krob
- [x]  1 Peter Hollands
- [x]  1 @danielwidmann
- [x]  1 @ssaamm
- [x]  1 Bryant Mairs
- [x]  1 Simon Wilks
- [x]  1 Lorenz Meier
- [x]  2 Dr.-Ing. Amilcar do Carmo Lucas
- [x]  2 Dirk Thomas
- [x]  3 Quy Tonthat
- [x]  3 Tim Ryan
- [x]  4 Huibean
- [x]  4 Eric Liao
- [x]  4 Sander Smeets
- [x]  7 Matthew Lloyd
- [x]  8 Pierre Kancir
- [x]  9  Patrick José Pereira
- [x]  9 Jonathan Challinger
- [x]  10 @pietrodn
- [ ]  15 Ben Nizette
- [x]  19 Jono Millin
- [x]  22 Jacob Walser
- [x]  26 Francisco Ferreira
- [x]  27 Bryant
- [x]  28 Kevin Hester
- [x]  30 Pat Hickey
- [x]  75 @squilter
- [x]  335 Peter Barker
- [x]  522 James Goppert
- [x]  1251 Andrew Tridgell

### CODE REVIEW

**Comment by OXINARF** [comment]
Ack from me.

**Comment by peterbarker** [comment]
Ack.

**Comment by amilcarlucas** [comment]
@jgoppert, @squilter, @pchickey, @geeksville, @bryant can you guys please give your OK to this?

**Comment by ssaamm** [comment]
I don't know if y'all need me to respond here, but just in case: I'm totally OK with any 
and all contributions I've made to this project being relicensed to LGPLv3+

**Comment by jgoppert** [comment]
Fine with me.

**Comment by amilcarlucas** [comment]
@hfujikawa77 also gave his OK on https://github.com/ArduPilot/pymavlink/commit/9fc5dfbebb0ee9a89d2c4de3169bc95735f7cb65#commitcomment-34066780

**Comment by pietrodn** [comment]
Ok for me.

**Comment by pchickey** [comment]
Ok for me

**Comment by amilcarlucas** [comment]
@matthewlloyd @khancyr @patrickelectric @jschall @benizl @jonomillin Can you guys also approve this one?

**Comment by khancyr** [comment]
ok for me

**Comment by patrickelectric** [comment]
I'm ok with it.

**Comment by amilcarlucas** [comment]
@matthewlloyd @jschall @benizl @jonomillin ping again

**Comment by jonomillin** [comment]
Fine with me!

**Comment by jschall** [comment]
K

**Comment by amilcarlucas** [comment]
@geeksville, @bryant, @sanderux , @eliao , @Huibean can you guys please give your permission?

**Comment by sanderux** [comment]
OK for me

**Comment by eliao** [comment]
Sure

**Comment by bryant** [comment]
k

**Comment by Huibean** [comment]
OK

**Comment by amilcarlucas** [comment]
@alexkrob, @phollands, @danielwidmann, @mairsbw @Susurrus, @sjwilks, @LorenzMeier, @dirk-thomas, @qtonthat @tcr3dr 
Do you guys also agree with this?

**Comment by phollands** [comment]
OK With me.

**Comment by dirk-thomas** [comment]
Ok with me.

**Comment by qtonthat** [comment]
Ok with me.

**Comment by geeksville** [comment]
fine with me

**Comment by Susurrus** [comment]
Fine with me.

**Comment by alexkrob** [comment]
Perfectly fine with me.

**Comment by amilcarlucas** [comment]
@danielwidmann @sjwilks @LorenzMeier @matthewlloyd @benizl we are still waiting for your answer on this.

**Comment by qtonthat** [comment]
On Wed, 2019-08-14 at 08:34 -0700, Amilcar Lucas wrote:
> @danielwidmann @sjwilks @LorenzMeier @matthewlloyd @benizl we are
> still waiting for your answer on this.
> 

OK with me.qt
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/ArduPilot/pymavlink/pull/329?email_source=notifications\u0026email_token=AAAVMFHDO6VUAHKTAWZOEYTQEQQXXA5CNFSM4HZSPE32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4JGAOI#issuecomment-521297977
> ",
> "url": "
> https://github.com/ArduPilot/pymavlink/pull/329?email_source=notifications\u0026email_token=AAAVMFHDO6VUAHKTAWZOEYTQEQQXXA5CNFSM4HZSPE32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4JGAOI#issuecomment-521297977
> ",
> "name": "View Pull Request"
> },
> "description": "View this Pull Request on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]

**Comment by matthewlloyd** [comment]
OK with me.

**Comment by danielwidmann** [comment]
OK with me.

**Comment by LorenzMeier** [comment]
Ok with me - the more adoption, the better.

**Comment by tcr** [comment]
OK with me!

**Comment by sjwilks** [comment]
OK with me

**Comment by amilcarlucas** [comment]
I tried to contact Ben Nizette multiple times, regarding the 15 lines of code that he contributed to this file, but got no answer. All the other 29 contributors agreed to this change. So .... committing it now.

**Comment by benizl** [comment]
No problem, ack.

**Pull request merged**
