### PR TITLE
Tools: allow to save extracted parameter with mavparms.py

### PR DESCRIPTION
**Pull request by khancyr**
add cmdline parameter to save parameter extracted !

### CODE REVIEW

**Comment by peterbarker** [comment]
What does this gain us vs just redirecting the output of the script?

I note that this *does* kill that functionality because of the print() messages present.

**Comment by khancyr** [comment]
@peterbarker, you made the assumption that everybody know how to redirect the output ! that is the difference ! Moreover, I am preparing a small GUI for Pymavlink tool so having parameter option is simpler. This is really intend to people not use to cmdline control  (and that a big part of user)
I will add # on each print so it won't break old behaviour

**Comment by peterbarker** [comment]
On Tue, 9 Oct 2018, Pierre Kancir wrote:

> @peterbarker, you made the assumption that everybody know how to redirect the output ! that is the difference ! Moreover, I am preparing a small GUI for
> Pymavlink tool so having parameter option is simpler. This is really intend to people not use to cmdline control (and that a big part of user)

In that case - shelling out to mavparms.py is probably the wrong approach 
:-)

**Comment by khancyr** [comment]
surely, but it will does the job for now ! It is not like I will get the time to do the GUI soon ^^ .
Are you good with the new option ?

**Comment by peterbarker** [comment]
On Wed, 10 Oct 2018, Pierre Kancir wrote:

> surely, but it will does the job for now ! It is not like I will get the time to do the GUI soon ^^ .
> Are you good with the new option ?

Sorry, I'm not in favour of this option - it's redundant with redirection.

**Comment by khancyr** [comment]
Ok then I close this

**Pull request closed without merging**
