### PR TITLE
mavgen_java.py: generate_enums: assume all integers to be 64 bits

### PR DESCRIPTION
**Pull request by TSC21**
Fixes https://github.com/ArduPilot/pymavlink/issues/638. Though I wonder if it is acceptable to use a larger data struct by default to enums just because of a single enumeration. Anyway we might eventually have other cases where this will happen.

### CODE REVIEW

**Comment by TSC21** [comment]
@peterbarker is this something you can review? Thanks in advance!

**Comment by peterbarker** [comment]
@TSC21 I haven't really dealt with these bindings much.

Perhaps @len0rd or @magicrub could comment?

**Comment by TSC21** [comment]
@len0rd @magicrub any chance you can help move this forward? Thanks!

**Review by magicrub — APPROVED** [review]
The one line change looks ok, but there's a ton of whitespace changes. They're good changes.. so that's ok.. but still kind of annoying. Anyway, it's likely worth merging.

**Comment by rrr6399** [comment]
This change breaks everybody's Java code and forces a int cast to the command enum when using it in a command. The large values are related to masks. The longs should only be used for masks.

**Pull request merged**
