### PR TITLE
Drop support for end of life versions of Python

### LINKED ISSUE #556: Drop support for Python 2
Python 2 died on more than 500 days ago on 1/1/2020 and should be considered an insecure platform.  Our installation and development processes are both more complicated because we still support legacy Python.

Current Python is v3.9.
https://devguide.python.org/#status-of-python-branches v.s.
https://devguide.python.org/devcycle/#end-of-life-branches

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #556
Fixes #555

This PR was created by running[`pyupgrade --py36-plus **/*.py`](https://github.com/asottile/pyupgrade) to drop support for [end of life](https://devguide.python.org/devcycle/#end-of-life-branches) versions of Python.
This removes 136 lines of legacy compatibility code while simplifying many other lines and given that [f-strings are faster](https://www.scivision.dev/python-f-string-speed) should speed up execution.   Adds README.md changes to streamline installation instructions.

### CODE REVIEW

**Comment by khancyr** [comment]
hello,

we won't drop support on python2.7 yet. There are still a good amount of people using it

**Comment by cclauss** [comment]
Closing.   Should I come back when legacy Python has been dead for 1,000 days?

**Comment by peterbarker** [comment]
On Fri, 18 Jun 2021, Christian Clauss wrote:

> Closing. Should I come back when legacy Python has been dead for 1,000 days?

Probably when the last Ubuntu LTS which installed Python2 by default is 
EOL.

Hopefully.

**Comment by cclauss** [comment]
April 2024 https://wiki.ubuntu.com/Releases

**Pull request closed without merging**
