### PR TITLE
Python 3 fixes to make DroneKit's tests run

### PR DESCRIPTION
**Pull request by pietrodn**
Here are some fixes which — together with [another PR in DroneKit](https://github.com/dronekit/dronekit-python/pull/784) — make DroneKit's SITL tests run also on Python 3.

This shouldn't break Python 2 compatibility (the tests run on Python 2).

### CODE REVIEW

**Comment by peterbarker** [comment]
ArduPilot's regression suite shows up some problems:

```
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_param.py", line 258, in handle_command
    self.mav_param.load(args[1], param_wildcard, master)
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.2.8-py2.7-linux-x86_64.egg/pymavlink/mavparm.py", line 88, in load
    if self.mavset(mav, a[0], a[1]):
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.2.8-py2.7-linux-x86_64.egg/pymavlink/mavparm.py", line 24, in mavset
    mav.param_set_send(name.upper(), float(value))
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.2.8-py2.7-linux-x86_64.egg/pymavlink/mavutil.py", line 417, in param_set_send
    bytes(parm_name, 'utf8'), parm_value, parm_type)
TypeError: str() takes at most 1 argument (2 given)
Mode MANUAL
APM: EKF2 IMU0 is using GPS
APM: EKF2 IMU1 is using GPS
```

**Comment by pietrodn** [comment]
The latest commit should fix the regression.

**Comment by peterbarker** [comment]
Squashed and pushed this in - thanks!

**Comment by peterbarker** [comment]
I should mention this does uglify mavlogdump's output a bit.  It's more correct but ugly ;-)

**Comment by pietrodn** [comment]
Thank you! Does it have to do with trailing null bytes?

**Comment by peterbarker** [comment]
On Mon, 22 Jan 2018, Pietro De Nicolao wrote:

> Thank you! Does it have to do with trailing null bytes?

Yes it does.

Should we trim those off somehow?

It's particularly noticable in statustext messages and parameter names.

**Comment by pietrodn** [comment]
I trimmed those in my other PR, in dronekit-python: https://github.com/dronekit/dronekit-python/pull/784/files

Maybe we can use the same solution, although I don’t know where to apply it in pymavlink codebase.

**Pull request closed without merging**
