### PR TITLE
PyMavlink : change shebangs to python3

### PR DESCRIPTION
**Pull request by kwikius**
See https://discuss.ardupilot.org/t/waf-update-waf-submodule-to-ardupilot-waf-master-user-setup-errror/113898

### CODE REVIEW

**Comment by davidbuzz** [comment]
why? anywhere that ardupilot supports running hthis, its already the case that python is python3 .?

**Comment by HTRamsey** [comment]
@davidbuzz at least then you don't need to create a symbolic link

**Comment by davidbuzz** [comment]
ubuntu/debian has: 
sudo update-alternatives --config python

**Comment by HTRamsey** [comment]
That's still creating a symbolic link. But regardless I was under the assumption that Python2 had been deprecated, which would mean there would be zero reason not to do this. Looking closer I see that Python2 is still supported and you're right this shouldn't be changed until after that is dropped

**Comment by kwikius** [comment]
Close stale PR

**Pull request closed without merging**
