### PR TITLE
mavutil.py: OFFBOARD mode interpretation fix

### PR DESCRIPTION
**Pull request by bkakilli**
OFFBOARD mode is interpreted as UNKNOWN.
Changing custom_sub_mode to custom_main_mode in line 1597 solves this issue.

### CODE REVIEW

**Comment by peterbarker** [comment]
I'm not sure that the check for this mode shouldn't go at the top of the `
 elif (base_mode & auto_mode_flags) == auto_mode_flags: #auto modes` block.

It seems odd that you'd have this comparison against the main mode where every other elif is checkout against teh submode.  I've only the loosest of understandings of how PX4 modes work, mind you....

@squilter Does this look right to you?  If not "right", will it do?

**Comment by bkakilli** [comment]
I checked the binary sequence of _base_mode_ and _control_mode of OFFBOARD mode_. auto_mode_flags = 00011100 and the _base_mode_ for OFFBOARD is 10011101. Therefore it passes that check you mentioned. And yeah, the comparison seems not consistent.

**Comment by squilter** [comment]
Yes, this looks correct.

**Comment by peterbarker** [comment]
Merged, thanks @bkakilli and @squilter

**Pull request merged**
