### PR TITLE
generator/mavgen.py: honour MDEF from environment in dynamic generation

### PR DESCRIPTION
**Pull request by peterbarker**
Closes https://github.com/ArduPilot/pymavlink/issues/596

### CODE REVIEW

**Comment by MauroPfister** [comment]
Hi @peterbarker, any chance this could be merged at some point?

**Comment by peterbarker** [comment]
> Hi @peterbarker, any chance this could be merged at some point?

Can you say that you've tested and that this does actually work for you?

**Comment by MauroPfister** [comment]
Yes, I can confirm that this is working on Ubuntu 22.04 and Python 3.10.7.

I installed pymavlink with `pip install .` from your branch and the message definitions from https://github.com/mavlink/mavlink. Then, I tested that the following code snippet works:

```python
from pymavlink import mavutil
import os

os.environ["MAVLINK20"] = "1"
os.environ["MDEF"] = "path_to_my_custom_message_definitions"

mavutil.set_dialect("my_custom_dialect")
```

**Comment by peterbarker** [comment]
> Yes, I can confirm that this is working on Ubuntu 22.04 and Python 3.10.7.
> 
> I installed pymavlink with `pip install .` from your branch and the message definitions from https://github.com/mavlink/mavlink. Then, I tested that the following code snippet works:
> 
> ```python
> from pymavlink import mavutil
> import os
> 
> os.environ["MAVLINK20"] = "1"
> os.environ["MDEF"] = "path_to_my_custom_message_definitions"
> 
> mavutil.set_dialect("my_custom_dialect")
> ```

Thanks for all of that!

I've merged this now.

**Pull request merged**
